config/routes.rb
RailsBlogChallengeNick::Application.routes.draw do
  root 'posts#index'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  get "/logout", to: "sessions#destroy"

  resources :posts, only: [:index, :show]
  resources :users do
    resources :posts, only: [:new, :create, :edit, :destroy]
  end


end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :email, :password, presence: true
  validates :username, uniqueness: true 
  validates :password, length: {minimum: 6}
  has_secure_password
  before_validation { self.password_confirmation ||= password }
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if current_user.posts.create(post_params)
      redirect_to root_url
    else
      @errors = @post.errors.full_messages
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to root_url
    else
      @errors = @post.errors.full_messages
      render "edit"
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post Deleted"
    redirect_to root_url
  end

  private

    def post_params
      params.require(:post).permit(:title, :content)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = "Welcome to the Build Up!"
      redirect_to user
    else
      @errors = ["Login information is incorrect"]
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password, :passwod_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Blog Challenge Nick Himmel</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Overpass:300,800" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <header>
    <div class="container">
      <h1 id="logo">The Build Up</h1>
      <nav>
        <ul class="main-nav">
          <li> <%= link_to('Home', root_path)%> </li>
          <li> <%= link_to('Sign Up', new_user_path)%> </li>
          <% if logged_in? %>
            <li> <%= current_user.username %> </li>
            <li> <%= link_to('Profile', current_user) %> </li>
            <li> <%= link_to('Logout', logout_path)%> </li>
          <% else %>
            <li> <%= link_to('Login', login_path)%> </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div> <%= render "shared/show" %> </div>
  <%= yield %>
</body>
<footer>
</footer>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h2>Edit Your Post</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 form-container">
      <%= render "shared/form" %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h2>All Posts</h2>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-6 form-container">
      <% if logged_in? %>
      <%= link_to "Add Post", new_user_post_path(current_user), :class => "btn btn-default" %>
      <% end %>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
      <%= render "shared/article" %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h2>Create New Post</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 form-container">
      <%= render "shared/form" %>
    </div>
  </div>
</div>

app/views/shared/_article.html.erb
<% @posts.each do |post| %>
  <article class="post">
   <h3 class="post_title"> <%= post.title %> </h3>
    <p class="date_author"> Posted <%= post.created_at.strftime("%A, %B %d %Y") %> by <%= post.user.username %> </p>
    <p class="post_content"> <%= post.content %> </p>
    <% if current_user?(post.user) %>
      <%= link_to "Edit", edit_user_post_path(post, post), :class => "btn btn-default edit-button" %>
      <%= link_to "Delete", user_post_path(post, post), method: :delete, :class => "btn btn-default edit-button" %>
    <% end %>
  </article>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @errors %>
  <ul>
    <% @errors.each do |error| %>
      <li class="errors" ><%= error %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_form.html.erb
<%= form_for(:post, url: user_posts_path) do |f| %>
  <%= render "shared/error_messages" %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, :class => "form-control", size: "24x6"%>
    </div>
  <%= f.submit "Post", :class => "btn btn-default" %>
<% end %>

app/views/shared/_show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> flash-alerts text-center"><%= message %></div>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h2>Sign Up</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-6 form-container"> 
      <%= form_for(@user) do |f| %>
        <%= render "shared/error_messages" %>
        <div class="form-group">
          <%= f.label :username %>
          <%= f.text_field :username, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, :class => "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation, :class => "form-control"%>
        </div>
        <%= f.submit "Create my account", :class => "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 form-container">
      <h2>Welcome</h2>
      <p class = "profile">Name: <%= @user.username %> </p>
      <p class = "profile">Email: <%= @user.email %> </p>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12">
      <h2>Your Posts</h2>
      <%= render "shared/article" %>
    </div>
  </div>
</div>